networks:
  monitor-net:
  
services:
  grafana:
    image: grafana/grafana:12.3.0-18329792253
    restart: always
    volumes:
      - ./grafana_data:/var/lib/grafana
    ports:
      - 9010:3000
    networks:
      - monitor-net
    depends_on:
      - prometheus

  prometheus:
    image: ubuntu/prometheus:2-24.04
    restart: always
    volumes:
      - ./prometheus_config/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9011:9090
    networks:
      - monitor-net
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.ignored-mount-points='^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var>
    ports:
      - 9012:9090
    networks:
      - monitor-net
    
